name: MadBoy

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "1078841825"

          replace: "1732236209"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Changed ID'

          commit_options: '--no-verify'

          repository: https://github.com/ULTRA-OP/ULTRA-X

          commit_user_name: madboy482
